/* ==========================================================
   TRASY – tu edytujesz treść planera.
   Każda trasa to jeden blok { ... }. Aby dodać trasę, skopiuj
   cały blok (od { do },), wklej pod spodem i zmień wartości.

   Pola:
   id         – krótka unikalna nazwa bez spacji i polskich liter
   typ        – "rower" albo "nordic"
   gdzie      – "blisko" (rower do 10 km / NW na miejscu)
                albo "dalej" (rower do 50 km / NW z dojazdem)
   nazwa      – tytuł trasy
   trudnosc   – lista: ["latwa"], ["srednia"], ["trudna"] lub np. ["latwa","srednia"]
   km         – liczba z KROPKĄ, np. 7.5
   czas       – tekst wyświetlany, np. "do 60 min"
   minuty     – przybliżony czas w minutach (do podsumowania planu)
   gondola    – true / false,  gondolaUwagi – tekst w nawiasie albo ""
   wozekBiegowy, dzieci, jedzenie – true / false
   dzieciOdLat – liczba albo null (gdy bez limitu wieku)
   opis       – lista akapitów; pierwszy widać zawsze, reszta po rozwinięciu
   wskazowka  – "Wskazówka od lokalsów"
   mapa       – pełny link do Komoot albo "" (pokaże „Mapa wkrótce”)
   zdjecia    – lista plików z folderu zdjecia; pierwsze to zdjęcie główne
   ========================================================== */

const TRASY = [
  {
    id: "karwia-las",
    typ: "rower",
    gdzie: "blisko",
    nazwa: "Leśna autostrada do Karwi",
    trudnosc: ["latwa"],
    km: 7.5,
    czas: "do 60 min",
    minuty: 60,
    gondola: false,
    gondolaUwagi: "zbyt wyboisto",
    wozekBiegowy: true,
    dzieci: true,
    dzieciOdLat: 6,
    jedzenie: true,
    opis: ["Szeroka, płaska ścieżka biegnąca w cieniu sosen tuż za wydmami.", "Idealna na bezpieczną, rodzinną przejażdżkę z dala od ruchu samochodowego, z możliwością zjechania prosto na szeroką plażę w Karwi."],
    wskazowka: "Najlepiej wybrać się tam rano. Latem unikniesz tłumów i zobaczysz pięknie oświetlony porannym słońcem las.",
    mapa: "https://www.komoot.com/pl-pl/tour/3288521560?share_token=a3LRpQdi76md98NZR1g2GpqPqKgXUQ8946t3VvoYSolPjx27qP",
    zdjecia: ["karwia-las-1.jpg", "karwia-las-2.jpg", "karwia-las-3.jpg"],
  },
  {
    id: "bielawskie",
    typ: "rower",
    gdzie: "blisko",
    nazwa: "Pętla wokół Bielawskich Błot",
    trudnosc: ["latwa"],
    km: 9.5,
    czas: "do 45 min",
    minuty: 45,
    gondola: false,
    gondolaUwagi: "piach i korzenie",
    wozekBiegowy: false,
    dzieci: true,
    dzieciOdLat: 10,
    jedzenie: false,
    opis: ["Dziki, unikalny rezerwat, gdzie z dala od zgiełku naładujesz baterie.", "Jesienią kwitną tu wrzosy, a krajobraz diametralnie różni się od plażowego wybrzeża. Wspaniała okazja na wycieczkę przyrodniczą z dziećmi."],
    wskazowka: "Zabierzcie na trasę lornetkę. To jedno z najlepszych i najspokojniejszych miejsc w regionie do obserwacji rzadkich gatunków ptaków.",
    mapa: "https://www.komoot.com/pl-pl/tour/3288675641?share_token=awCisprZyYWdnt2S2PIWhypdsb5Ia6FwJ6vkOoO623X4nf8axN",
    zdjecia: ["bielawskie-1.jpg", "bielawskie-2.jpg", "bielawskie-3.jpg"],
  },
  {
    id: "latarnia",
    typ: "rower",
    gdzie: "blisko",
    nazwa: "Szlakiem Latarni Morskiej w Rozewiu",
    trudnosc: ["latwa"],
    km: 2.5,
    czas: "ponad 45 min",
    minuty: 45,
    gondola: false,
    gondolaUwagi: "leśne ścieżki",
    wozekBiegowy: true,
    dzieci: true,
    dzieciOdLat: 8,
    jedzenie: false,
    opis: ["Trasa łączy urok nadmorskiego lasu z możliwością zobaczenia jednej z latarni morskich na ich nadmorskim szlaku.", "Po drodze czeka kilka łagodnych wzniesień, piękny rezerwat ponad stuletnich buków, a na mecie imponująca latarnia morska."],
    wskazowka: "Zabierzcie drobne na wstęp do latarni. Widok z tarasu na Bałtyk i Półwysep Helski jest wart wysiłku!",
    mapa: "https://www.komoot.com/pl-pl/tour/3288598341?share_token=aOUMJ5ihXHlc1SDpkTNnIRft1tIOgFH9zXo0zEp8AyFe99JL21",
    zdjecia: ["latarnia-1.jpg", "latarnia-2.jpg", "latarnia-3.jpg"],
  },
  {
    id: "chlapowo",
    typ: "rower",
    gdzie: "blisko",
    nazwa: "Do Chłapowa z przystankiem w Lisim Jarze",
    trudnosc: ["srednia"],
    km: 10,
    czas: "90 min",
    minuty: 90,
    gondola: false,
    gondolaUwagi: "stromo",
    wozekBiegowy: false,
    dzieci: true,
    dzieciOdLat: 12,
    jedzenie: false,
    opis: ["Głęboki wąwóz zachwyca specyficznym mikroklimatem i majestatycznymi drzewami.", "Trasa bywa stroma i wąska, ale wyjazd z jaru prosto na plażę i widok na wysokie klify chłapowskie wynagradzają każdą kroplę potu."],
    wskazowka: "Na stromych, piaszczystych zjazdach wewnątrz jaru dla bezpieczeństwa (zwłaszcza z dziećmi) sprowadźcie rowery.",
    mapa: "",
    zdjecia: ["chlapowo-1.jpg", "chlapowo-2.jpg", "chlapowo-3.jpg"],
  },
  {
    id: "hel-rower",
    typ: "rower",
    gdzie: "dalej",
    nazwa: "Ścieżka w stronę Półwyspu Helskiego (do Jastarni)",
    trudnosc: ["srednia"],
    km: 30,
    czas: "3 godziny",
    minuty: 180,
    gondola: false,
    gondolaUwagi: "",
    wozekBiegowy: true,
    dzieci: true,
    dzieciOdLat: 10,
    jedzenie: true,
    opis: ["Kultowa, nadmorska trasa rowerowa biegnąca wzdłuż wód Zatoki Puckiej.", "Cały czas jedziecie płaskim, asfaltowym lub wyłożonym kostką szlakiem, mijając zatoczki, mariny i setki kolorowych latawców kitesurfingowych."],
    wskazowka: "Jeśli wystarczy Wam sił, warto popedałować odrobinę dalej do Juraty. Trasa w większości jest bardzo malownicza, aż do samego Helu.",
    mapa: "https://www.komoot.com/pl-pl/tour/3289646376?share_token=aWgXDUacl6CUpQjJGDM5mcseEwFwAd6GV5SMr3Q866zsa9pn1d",
    zdjecia: ["hel-rower-1.jpg", "hel-rower-2.jpg", "hel-rower-3.jpg"],
  },
  {
    id: "krokowa",
    typ: "rower",
    gdzie: "dalej",
    nazwa: "Trasą „Zwiniętych Torów” do Krokowej",
    trudnosc: ["latwa", "srednia"],
    km: 15,
    czas: "1,5 godziny",
    minuty: 90,
    gondola: false,
    gondolaUwagi: "",
    wozekBiegowy: true,
    dzieci: true,
    dzieciOdLat: 8,
    jedzenie: true,
    opis: ["Wyjątkowa ścieżka wylana idealnie gładkim asfaltem na dawnym nasypie kolejowym.", "Szlak jest całkowicie odseparowany od samochodów, ma minimalne przewyższenia i prowadzi prosto pod piękny zamek w Krokowej."],
    wskazowka: "Warto zaplanować postój w kawiarni na Zamku w Krokowej, zanim ruszycie w drogę powrotną.",
    mapa: "https://www.komoot.com/pl-pl/tour/3289642940?share_token=a1aHHRjMEtaNyEy2JzxML31ph4SrRYvRRKT2RJLrgT4cQktV7y",
    zdjecia: ["krokowa-1.jpg", "krokowa-2.jpg"],
  },
  {
    id: "rzucewo",
    typ: "rower",
    gdzie: "dalej",
    nazwa: "Szlak na Zamek w Rzucewie przez Puck",
    trudnosc: ["srednia"],
    km: 27,
    czas: "2 godziny",
    minuty: 120,
    gondola: false,
    gondolaUwagi: "",
    wozekBiegowy: false,
    dzieci: true,
    dzieciOdLat: 12,
    jedzenie: true,
    opis: ["Zjawiskowy szlak od Swarzewa, prowadzący krawędzią klifu tuż nad Zatoką Pucką.", "Trasa jest bardzo zróżnicowana, od leśnych ścieżek przez polne drogi, a jej zwieńczeniem jest neogotycki zamek otoczony starym parkiem."],
    wskazowka: "Szlak tuż nad zatoką może być błotnisty po deszczach. Najlepiej wybrać się tam po co najmniej dwóch dniach suchej, słonecznej pogody.",
    mapa: "https://www.komoot.com/pl-pl/tour/3289631187?share_token=aK1axiDpVUaP66R38jDUIzFQc4bCNW08Ssu8DEAece3XIP1fPf",
    zdjecia: ["rzucewo-1.jpg", "rzucewo-2.jpg", "rzucewo-3.jpg"],
  },
  {
    id: "mechowo",
    typ: "rower",
    gdzie: "dalej",
    nazwa: "Przez Puszczę Darżlubską do Grot Mechowskich",
    trudnosc: ["srednia"],
    km: 17,
    czas: "2 godziny",
    minuty: 120,
    gondola: false,
    gondolaUwagi: "",
    wozekBiegowy: false,
    dzieci: false,
    dzieciOdLat: null,
    jedzenie: false,
    opis: ["Propozycja dla miłośników przyrody, cienia i jazdy terenowej, prowadząca do fascynującego i unikalnego miejsca.", "Grota Mechowska to jedyna w Polsce i Europie osobliwość geologiczna powstała na terenach nizinnych."],
    wskazowka: "W głębi puszczy brakuje zasięgu i sklepów. Pobierzcie mapę offline na telefon i weźcie ze sobą odpowiedni zapas wody oraz jedzenia.",
    mapa: "https://www.komoot.com/pl-pl/tour/3289649827?share_token=aEeJv08kDwL0TKqEdeo5wff4gLiw8srKLJaZVSZNTwXlxL3MHj",
    zdjecia: ["mechowo-1.jpg", "mechowo-2.jpg", "mechowo-3.jpg"],
  },
  {
    id: "faleza",
    typ: "nordic",
    gdzie: "blisko",
    nazwa: "W stronę Hotelu Faleza",
    trudnosc: ["latwa"],
    km: 2.6,
    czas: "do 45 min",
    minuty: 45,
    gondola: true,
    gondolaUwagi: "",
    wozekBiegowy: true,
    dzieci: true,
    dzieciOdLat: null,
    jedzenie: true,
    opis: ["Malownicza, ale niewymagająca trasa. Idealna na spacer z dziećmi oraz czworonożnymi pupilami.", "Dość popularna w sezonie letnim, jesienią i zimą cichnie i nabiera przepięknych, złotoczerwonych barw."],
    wskazowka: "Trasa idealna na „przystawkę” przed obiadem lub kolacją w całorocznej restauracji w hotelu Faleza.",
    mapa: "https://www.komoot.com/pl-pl/tour/3289678721?share_token=aDHHkdTsxJBp72lyL6S5hmC5loBOGinYT8Ruh9iR2uFcniXbe3",
    zdjecia: ["faleza-1.jpg", "faleza-2.jpg", "faleza-3.jpg"],
  },
  {
    id: "lisi-jar",
    typ: "nordic",
    gdzie: "blisko",
    nazwa: "Magia Lisiego Jaru",
    trudnosc: ["srednia"],
    km: 2,
    czas: "do 45 min",
    minuty: 45,
    gondola: false,
    gondolaUwagi: "",
    wozekBiegowy: false,
    dzieci: true,
    dzieciOdLat: null,
    jedzenie: false,
    opis: ["Krótki, ale niezwykle satysfakcjonujący marsz z solidnym treningiem na podejściach.", "Wąwóz tonie w cieniu pomnikowych buków, dając schronienie przed upałem i tworząc baśniowy, spokojny nastrój."],
    wskazowka: "Na odcinkach utwardzonych użyj gumowych nakładek na groty kijków, ale w samym jarze zdejmij je, by zyskać lepsze odbicie na leśnej ściółce.",
    mapa: "https://www.komoot.com/pl-pl/tour/3289728199?share_token=aPnNtPClGD0NXi9G5BRAybSU4OXVSNTPH3U1kAQUxUmhsnA93F",
    zdjecia: ["lisi-jar-1.jpg", "lisi-jar-2.jpg", "lisi-jar-3.jpg"],
  },
  {
    id: "karwia-plaza",
    typ: "nordic",
    gdzie: "blisko",
    nazwa: "Plażą do Karwi i powrót lasem",
    trudnosc: ["srednia", "trudna"],
    km: 7,
    czas: "2 godziny",
    minuty: 120,
    gondola: false,
    gondolaUwagi: "",
    wozekBiegowy: false,
    dzieci: true,
    dzieciOdLat: null,
    jedzenie: false,
    opis: ["Klasyczny trening interwałowy. Marsz w puszystym piasku w jedną stronę angażuje całe ciało i mocno podnosi tętno.", "Powrót ubitą ścieżką sosnowego lasu to czysty relaks i szansa na wydłużenie kroku."],
    wskazowka: "Na odcinkach utwardzonych użyj gumowych nakładek na groty kijków, ale w samym jarze zdejmij je, by zyskać lepsze odbicie na leśnej ściółce.",
    mapa: "https://www.komoot.com/pl-pl/tour/3289796587?share_token=aIQzrxnU2hC7bJ1dlSAoj0oebowRb01fhV1Sz00SdfBq85Hc79",
    zdjecia: ["karwia-plaza-1.jpg", "karwia-plaza-2.jpg", "karwia-plaza-3.jpg"],
  },
  {
    id: "rozewie",
    typ: "nordic",
    gdzie: "blisko",
    nazwa: "Rezerwat Przylądek Rozewie",
    trudnosc: ["latwa"],
    km: 3,
    czas: "45 min",
    minuty: 45,
    gondola: false,
    gondolaUwagi: "",
    wozekBiegowy: true,
    dzieci: true,
    dzieciOdLat: null,
    jedzenie: false,
    opis: ["Zalesiony, zjawiskowy odcinek tuż przy starej latarni morskiej.", "Miękkie, liściaste podłoże idealnie amortyzuje uderzenia kijków, pozwalając w 100% skupić się na prawidłowej technice marszu."],
    wskazowka: "Zejdźcie schodami na dół wąwozu prosto na plażę. Znajduje się tam betonowa opaska ochronna u stóp klifu, po której wspaniale maszeruje się tuż przy falach.",
    mapa: "",
    zdjecia: ["rozewie-1.jpg", "rozewie-2.jpg", "rozewie-3.jpg"],
  },
  {
    id: "wawoz",
    typ: "nordic",
    gdzie: "blisko",
    nazwa: "Wąwóz Chłapowski",
    trudnosc: ["latwa"],
    km: 4,
    czas: "60 min",
    minuty: 60,
    gondola: false,
    gondolaUwagi: "",
    wozekBiegowy: true,
    dzieci: true,
    dzieciOdLat: null,
    jedzenie: false,
    opis: ["Niezwykle zróżnicowana krajobrazowo dolina polodowcowa, prowadząca malowniczo wyrzeźbionym korytem aż do Bałtyku.", "Szlak urozmaicony jest schodkami, głazami i rzadką roślinnością."],
    wskazowka: "Wiosną i wczesnym latem rozkwitają tu zarośla żarnowca. Cały wąwóz mieni się wtedy na żółto.",
    mapa: "https://www.komoot.com/pl-pl/tour/3289808694?share_token=aJECXeIFcrGkcqHnPdsa6XYiSRaK8MLB6kCh8Sm36qrfepK7dY",
    zdjecia: ["wawoz-1.jpg", "wawoz-2.jpg", "wawoz-3.jpg"],
  },
  {
    id: "beka",
    typ: "nordic",
    gdzie: "dalej",
    nazwa: "Rezerwat Beka (okolice Osłonina)",
    trudnosc: ["latwa"],
    km: 4,
    czas: "2 godziny",
    minuty: 120,
    gondola: false,
    gondolaUwagi: "",
    wozekBiegowy: true,
    dzieci: true,
    dzieciOdLat: null,
    jedzenie: false,
    opis: ["Płaskie, rozległe słone łąki dają złudzenie spaceru na krańcach świata.", "Brak przewyższeń pozwala na wdrożenie długiego, sportowego kroku w równym tempie dla efektywnego treningu."],
    wskazowka: "Obszar słynie z olbrzymiej liczby ptaków brodzących. Koniecznie weźcie ze sobą lornetkę i zaplanujcie krótką przerwę przy wieżach widokowych.",
    mapa: "https://www.komoot.com/pl-pl/tour/3289817647?share_token=aaGfPsLjrHHPtxZ4XTyNoiov3Qq6J8I2kGm4VXc9dY1aey5ztp",
    zdjecia: ["beka-1.jpg", "beka-2.jpg", "beka-3.jpg"],
  },
  {
    id: "cypel",
    typ: "nordic",
    gdzie: "dalej",
    nazwa: "Cypel Helski i ścieżka militarna",
    trudnosc: ["latwa"],
    km: 4,
    czas: "1–2 godziny",
    minuty: 90,
    gondola: false,
    gondolaUwagi: "",
    wozekBiegowy: true,
    dzieci: true,
    dzieciOdLat: null,
    jedzenie: false,
    opis: ["Sieć świetnie utrzymanych kładek i ścieżek edukacyjnych na samym koniuszku Mierzei Helskiej.", "Poprowadzi Was wzdłuż dawnych fortyfikacji i baterii obronnych."],
    wskazowka: "Zanim wybierzecie się na wycieczkę tym militarnym szlakiem, warto odświeżyć sobie historię tego miejsca.",
    mapa: "https://www.komoot.com/pl-pl/tour/3289824843?share_token=aP5c92BVKvla07CR4CnJqCKIaZNTfWHRyqA4DgmQZqYsCy8464",
    zdjecia: ["cypel-1.jpg", "cypel-2.jpg", "cypel-3.jpg"],
  },
  {
    id: "piasnica",
    typ: "nordic",
    gdzie: "dalej",
    nazwa: "Puszcza Darżlubska (Lasy Piaśnickie)",
    trudnosc: ["trudna"],
    km: 4,
    czas: "1–2 godziny",
    minuty: 90,
    gondola: false,
    gondolaUwagi: "",
    wozekBiegowy: false,
    dzieci: false,
    dzieciOdLat: null,
    jedzenie: false,
    opis: ["Nieskończone szpalery drzew i szerokie leśne ścieżki to dobre miejsce na długi, wytrzymałościowy marsz.", "Las Piaśnicki to również miejsce bardzo trudnej historii, którą zdecydowanie warto poznać, zanim wybierzecie się na spacer po tych terenach."],
    wskazowka: "Ponieważ leśne skrzyżowania bywają do siebie bardzo podobne, pobierz ślad GPS trasy (w formacie GPX) do swojego zegarka sportowego lub aplikacji.",
    mapa: "https://www.komoot.com/pl-pl/tour/3289842327?share_token=aAIHoWf2AAjHDvwtI9z20ireDjau7eMhiHsIgQXVP1B8mxGQ41",
    zdjecia: ["piasnica-1.jpg", "piasnica-2.jpg", "piasnica-3.jpg"],
  },
];
